"""implemented relationships between two tables

Revision ID: 86dc50ebe250
Revises: 94f57f9612df
Create Date: 2023-06-22 13:42:44.365517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dc50ebe250'
down_revision = '94f57f9612df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_videos_user_id_users_id", 'users', ['fk_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint("fk_videos_user_id_users_id", type_='foreignkey')
        batch_op.drop_column('fk_user_id')

    # ### end Alembic commands ###
