"""added date_col(comments)&description(videos)

Revision ID: 8e7e5eeaab65
Revises: e85fbbd0a23e
Create Date: 2023-06-23 17:03:57.760460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7e5eeaab65'
down_revision = 'e85fbbd0a23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=15), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
