"""Added column video_name to table videos

Revision ID: d10f9b258ec5
Revises: 86dc50ebe250
Create Date: 2023-06-22 13:57:56.727969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10f9b258ec5'
down_revision = '86dc50ebe250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_name', sa.String(length=45), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('video_name')

    # ### end Alembic commands ###
